// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arphbkahupbfzcnluiwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycGhia2FodXBiZnpjbmx1aXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjU4MzgsImV4cCI6MjA2MzIwMTgzOH0.0NMnPRGxw1bO_dQHfMeP8_Dz8rIsJ0lCOY2JgopUKPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);